apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: "argus"
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
data:
  config.yaml: |
    address: collectorset-controller:50000
    cluster_name: {{ required "A valid .Values.clusterName entry is required!" .Values.clusterName }}
    debug: {{ required "A valid .Values.debug entry is required!" .Values.debug }}
    delete_devices: {{ required "A valid .Values.deleteDevices entry is required!" .Values.deleteDevices }}
    disable_alerting: {{ required "A valid .Values.disableAlerting entry is required!" .Values.disableAlerting }}
    etcd_discovery_token: {{ .Values.etcdDiscoveryToken }}
    cluster_group_id: {{ .Values.clusterGroupID }}
    {{- if .Values.proxyURL }}
    proxy_url: {{ .Values.proxyURL }}
    {{- end }}
  rl-policy.yaml: |
    device:
      get:
        pod: 70
        dep: 10
        svc: 10
        node: 10
      post:
        pod: 70
        dep: 10
        svc: 10
        node: 10
      put:
        pod: 70
        dep: 10
        svc: 10
        node: 10
      patch:
        pod: 70
        dep: 10
        svc: 10
        node: 10
      delete:
        pod: 70
        dep: 10
        svc: 10
        node: 10
  filters-config.yaml: |
    filter:
      pods: {{ .Values.filters.pod }}
      services: {{ .Values.filters.service }}
      deployments: {{ .Values.filters.deployment }}
      nodes: {{ .Values.filters.node }}
