apiVersion: v1
kind: ConfigMap
metadata:
  name: argus
data:
  config.yaml: |
    address: collectorset-controller:50000
    cluster_name: {{ required "A valid .Values.clusterName entry is required!" .Values.clusterName }}
    debug: {{ required "A valid .Values.debug entry is required!" .Values.debug }}
    delete_devices: {{ required "A valid .Values.deleteDevices entry is required!" .Values.deleteDevices }}
    disable_alerting: {{ required "A valid .Values.disableAlerting entry is required!" .Values.disableAlerting }}
    etcd_discovery_token: {{ .Values.etcdDiscoveryToken }}
    cluster_group_id: {{ .Values.clusterGroupID }}
    {{- if .Values.proxyURL }}
    proxy_url: {{ .Values.proxyURL }}
    {{- end }}